/**
 * agency-names.ts
 *
 * Acronym → full name lookup for federal agencies.
 *
 * Why this exists: the agencies table stores name = acronym for many rows
 * (the regulations.gov pipeline does not receive full names from the API).
 * This map is the authoritative source until the DB is corrected.
 *
 * Coverage: all 82 active agencies currently in the DB (as of 2026-03-18),
 * plus common extras for resilience.
 *
 * Usage: import { AGENCY_NAMES, agencyFullName } from "@civitics/db";
 */

export const AGENCY_NAMES: Record<string, string> = {
  ACF:     "Administration for Children and Families",
  AMS:     "Agricultural Marketing Service",
  APHIS:   "Animal and Plant Health Inspection Service",
  ATBCB:   "Architectural and Transportation Barriers Compliance Board",
  ATF:     "Bureau of Alcohol, Tobacco, Firearms and Explosives",
  BIA:     "Bureau of Indian Affairs",
  BLM:     "Bureau of Land Management",
  BOEM:    "Bureau of Ocean Energy Management",
  BOP:     "Bureau of Prisons",
  BOR:     "Bureau of Reclamation",
  BIS:     "Bureau of Industry and Security",
  BSEE:    "Bureau of Safety and Environmental Enforcement",
  CBP:     "U.S. Customs and Border Protection",
  CDC:     "Centers for Disease Control and Prevention",
  CFPB:    "Consumer Financial Protection Bureau",
  CFTC:    "Commodity Futures Trading Commission",
  CISA:    "Cybersecurity and Infrastructure Security Agency",
  CMS:     "Centers for Medicare & Medicaid Services",
  COE:     "U.S. Army Corps of Engineers",
  CPSC:    "Consumer Product Safety Commission",
  CRB:     "Copyright Royalty Board",
  DARS:    "Defense Acquisition Regulations System",
  DEA:     "Drug Enforcement Administration",
  DNFSB:   "Defense Nuclear Facilities Safety Board",
  DOC:     "Department of Commerce",
  DOD:     "Department of Defense",
  DOE:     "Department of Energy",
  DOI:     "Department of the Interior",
  DOJ:     "Department of Justice",
  DOL:     "Department of Labor",
  DOS:     "Department of State",
  DOT:     "Department of Transportation",
  EBSA:    "Employee Benefits Security Administration",
  ED:      "Department of Education",
  EEOC:    "Equal Employment Opportunity Commission",
  EERE:    "Office of Energy Efficiency and Renewable Energy",
  EPA:     "Environmental Protection Agency",
  ETA:     "Employment and Training Administration",
  FAA:     "Federal Aviation Administration",
  FAR:     "Federal Acquisition Regulation",
  FBI:     "Federal Bureau of Investigation",
  FCA:     "Farm Credit Administration",
  FCC:     "Federal Communications Commission",
  FDA:     "Food and Drug Administration",
  FDIC:    "Federal Deposit Insurance Corporation",
  FEMA:    "Federal Emergency Management Agency",
  FERC:    "Federal Energy Regulatory Commission",
  FHFA:    "Federal Housing Finance Agency",
  FINCEN:  "Financial Crimes Enforcement Network",
  FISCAL:  "Bureau of the Fiscal Service",
  FLRA:    "Federal Labor Relations Authority",
  FMCSA:   "Federal Motor Carrier Safety Administration",
  FNS:     "Food and Nutrition Service",
  FPPO:    "Federal Procurement Policy Office",
  FRS:     "Federal Reserve System",
  FRTIB:   "Federal Retirement Thrift Investment Board",
  FS:      "U.S. Forest Service",
  FSIS:    "Food Safety and Inspection Service",
  FTA:     "Federal Transit Administration",
  FTC:     "Federal Trade Commission",
  FWS:     "U.S. Fish and Wildlife Service",
  GSA:     "General Services Administration",
  HHS:     "Department of Health and Human Services",
  HHSIG:   "HHS Office of Inspector General",
  HUD:     "Department of Housing and Urban Development",
  ICEB:    "ICE Enforcement and Removal Operations",
  IRS:     "Internal Revenue Service",
  MARAD:   "Maritime Administration",
  MSHA:    "Mine Safety and Health Administration",
  NASA:    "National Aeronautics and Space Administration",
  NCUA:    "National Credit Union Administration",
  NHTSA:   "National Highway Traffic Safety Administration",
  NIH:     "National Institutes of Health",
  NLRB:    "National Labor Relations Board",
  NMFS:    "National Marine Fisheries Service",
  NOAA:    "National Oceanic and Atmospheric Administration",
  NPS:     "National Park Service",
  NRC:     "Nuclear Regulatory Commission",
  NSF:     "National Science Foundation",
  OCC:     "Office of the Comptroller of the Currency",
  OFCCP:   "Office of Federal Contract Compliance Programs",
  OMB:     "Office of Management and Budget",
  OPM:     "Office of Personnel Management",
  OSHA:    "Occupational Safety and Health Administration",
  OSM:     "Office of Surface Mining Reclamation and Enforcement",
  PBGC:    "Pension Benefit Guaranty Corporation",
  PHMSA:   "Pipeline and Hazardous Materials Safety Administration",
  PRC:     "Postal Regulatory Commission",
  PTO:     "U.S. Patent and Trademark Office",
  RUS:     "Rural Utilities Service",
  SBA:     "Small Business Administration",
  SEC:     "Securities and Exchange Commission",
  SSA:     "Social Security Administration",
  STB:     "Surface Transportation Board",
  TREAS:   "Department of the Treasury",
  TSA:     "Transportation Security Administration",
  TTB:     "Alcohol and Tobacco Tax and Trade Bureau",
  USBC:    "U.S. Census Bureau",
  USCBP:   "U.S. Customs and Border Protection",
  USCG:    "U.S. Coast Guard",
  USCIS:   "U.S. Citizenship and Immigration Services",
  USDA:    "U.S. Department of Agriculture",
  USFWS:   "U.S. Fish and Wildlife Service",
  USPS:    "U.S. Postal Service",
  VA:      "Department of Veterans Affairs",
  WCPO:    "Workers' Compensation Programs Office",
  WHD:     "Wage and Hour Division",
};

/**
 * Returns the full agency name for a given acronym,
 * falling back to the acronym itself if not found.
 */
export function agencyFullName(acronym: string | null | undefined): string | null {
  if (!acronym) return null;
  return AGENCY_NAMES[acronym.toUpperCase()] ?? acronym;
}
