/**
 * Static map of federal agency acronyms → full names.
 * Regulations.gov stores only the acronym in proposals.metadata.agency_id,
 * and the data pipeline upserts agencies with name=acronym (no full-name API).
 * This map is the source of truth for display purposes.
 */
export const AGENCY_FULL_NAMES: Record<string, string> = {
  // High-volume Regulations.gov agencies
  FAA:    "Federal Aviation Administration",
  EPA:    "Environmental Protection Agency",
  USCG:   "US Coast Guard",
  FCC:    "Federal Communications Commission",
  FWS:    "Fish and Wildlife Service",
  NOAA:   "National Oceanic and Atmospheric Administration",
  IRS:    "Internal Revenue Service",
  NCUA:   "National Credit Union Administration",
  OSHA:   "Occupational Safety and Health Administration",
  AMS:    "Agricultural Marketing Service",
  CMS:    "Centers for Medicare & Medicaid Services",
  OCC:    "Office of the Comptroller of the Currency",
  NRC:    "Nuclear Regulatory Commission",
  ED:     "Department of Education",
  FERC:   "Federal Energy Regulatory Commission",
  OPM:    "Office of Personnel Management",
  FDA:    "Food and Drug Administration",
  VA:     "Department of Veterans Affairs",
  CPSC:   "Consumer Product Safety Commission",
  NHTSA:  "National Highway Traffic Safety Administration",
  // Additional common agencies
  USDA:   "US Department of Agriculture",
  HUD:    "Dept. of Housing and Urban Development",
  DOT:    "Department of Transportation",
  DOD:    "Department of Defense",
  DOJ:    "Department of Justice",
  DOS:    "Department of State",
  DOE:    "Department of Energy",
  HHS:    "Dept. of Health and Human Services",
  DHS:    "Department of Homeland Security",
  DOL:    "Department of Labor",
  DOI:    "Department of the Interior",
  TREAS:  "Department of the Treasury",
  SEC:    "Securities and Exchange Commission",
  CFTC:   "Commodity Futures Trading Commission",
  FTC:    "Federal Trade Commission",
  CFPB:   "Consumer Financial Protection Bureau",
  FMCSA:  "Federal Motor Carrier Safety Administration",
  PHMSA:  "Pipeline and Hazardous Materials Safety Admin.",
  FHWA:   "Federal Highway Administration",
  FRA:    "Federal Railroad Administration",
  FTA:    "Federal Transit Administration",
  MARAD:  "Maritime Administration",
  NTSB:   "National Transportation Safety Board",
  TSA:    "Transportation Security Administration",
  CBP:    "Customs and Border Protection",
  ICE:    "Immigration and Customs Enforcement",
  FEMA:   "Federal Emergency Management Agency",
  USSS:   "United States Secret Service",
  ATF:    "Bureau of Alcohol, Tobacco, Firearms",
  DEA:    "Drug Enforcement Administration",
  FBI:    "Federal Bureau of Investigation",
  BOP:    "Bureau of Prisons",
  USCIS:  "US Citizenship and Immigration Services",
  BLS:    "Bureau of Labor Statistics",
  MSHA:   "Mine Safety and Health Administration",
  WHD:    "Wage and Hour Division",
  NLRB:   "National Labor Relations Board",
  EEOC:   "Equal Employment Opportunity Commission",
  PBGC:   "Pension Benefit Guaranty Corporation",
  SSA:    "Social Security Administration",
  CDC:    "Centers for Disease Control and Prevention",
  NIH:    "National Institutes of Health",
  ACF:    "Administration for Children and Families",
  HRSA:   "Health Resources and Services Administration",
  SAMHSA: "Substance Abuse and Mental Health Services Admin.",
  ACL:    "Administration for Community Living",
  IHS:    "Indian Health Service",
  BLM:    "Bureau of Land Management",
  NPS:    "National Park Service",
  USFWS:  "US Fish and Wildlife Service",
  BIA:    "Bureau of Indian Affairs",
  OSMRE:  "Office of Surface Mining Reclamation",
  BOEM:   "Bureau of Ocean Energy Management",
  BSEE:   "Bureau of Safety and Environmental Enforcement",
  BOR:    "Bureau of Reclamation",
  USGS:   "US Geological Survey",
  FS:     "US Forest Service",
  NRCS:   "Natural Resources Conservation Service",
  RMA:    "Risk Management Agency",
  FNS:    "Food and Nutrition Service",
  FSIS:   "Food Safety and Inspection Service",
  APHIS:  "Animal and Plant Health Inspection Service",
  RUS:    "Rural Utilities Service",
  FSA:    "Farm Service Agency",
  ERS:    "Economic Research Service",
  NIFA:   "National Institute of Food and Agriculture",
  NASS:   "National Agricultural Statistics Service",
  FHFA:   "Federal Housing Finance Agency",
  FDIC:   "Federal Deposit Insurance Corporation",
  FRB:    "Federal Reserve Board",
  CISA:   "Cybersecurity and Infrastructure Security Agency",
  NGA:    "National Geospatial-Intelligence Agency",
  GSA:    "General Services Administration",
  SBA:    "Small Business Administration",
  NASA:   "National Aeronautics and Space Administration",
  NSF:    "National Science Foundation",
  NIST:   "National Institute of Standards and Technology",
  USPTO:  "US Patent and Trademark Office",
  NTIA:   "National Telecommunications and Information Admin.",
  BIS:    "Bureau of Industry and Security",
  ITA:    "International Trade Administration",
  USTR:   "Office of US Trade Representative",
  USAID:  "US Agency for International Development",
  EXIM:   "Export-Import Bank",
  MCC:    "Millennium Challenge Corporation",
  OPIC:   "Overseas Private Investment Corporation",
  PCC:    "Peace Corps",
  NMB:    "National Mediation Board",
  FLRA:   "Federal Labor Relations Authority",
  MSPB:   "Merit Systems Protection Board",
  USITC:  "US International Trade Commission",
};
